### ISSUE TITLE
`withLocalPlugin` doesn't work properly with scoped names

### ISSUE THREAD

**Issue by masnagam** [vowstar/honkit-tester#1]
The following code causes an `ENOENT` error:

```js
tester
  .build()
  .withLocalPlugin('/path/to/plugin')
  .create()
  ...
```

where `/path/to/plugin/package.json`:

```json
{
  "name": "@scoped/plugin",
  ...
}
```

`honkit-tester` tries to create a symbolic link called `@scoped/plugin`, but there is no `@scoped` directory.

If the plugin name has a scope, it's necessary to create a directory for the scope before creating a symbolic link:
https://github.com/vowstar/honkit-tester/blob/master/lib/tester.js#L181

**Comment by vowstar** [comment]
Yes it is a bug, if it have a "@scoped/", the directory must create before do symbolic link.

**Comment by vowstar** [comment]
@masnagam Fixed. Please check again.

**Comment by masnagam** [comment]
@vowstar Confirmed that the problem has been fixed.  Thank you!
